### ISSUE TITLE
Timeout error occurs when transaction signature has been sitting too long

### ISSUE THREAD

**Issue by Schwartz10** [ChainSafe/filsnap#97] opened 2022-01-07 16:39 UTC
1. Invoke a signature request 
2. Wait a long time
3. Sign it

Request "times out"

**Comment by BeroBurny** [comment] 2022-04-28 12:55
Currently is not possible to fix this as-is implementation issue on snap, will be left open as a reminder to fix it when will be possible

**Comment by mpetrunic** [comment] 2022-05-03 08:10
duplicate of https://github.com/ChainSafe/filsnap/issues/130

**Closed by mpetrunic** 2022-05-03 08:10 UTC
Labels: wontfix
